# Generated by Django 6.0.6 on 2026-07-02 07:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مهمانی')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('venue_name', models.CharField(max_length=200, verbose_name='نام مکان برگزاری')),
                ('event_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('event_time', models.TimeField(verbose_name='ساعت شروع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار برگزاری'), ('active', 'در حال برگزاری'), ('completed', 'پایان یافته')], default='pending', max_length=20, verbose_name='وضعیت مهمانی')),
                ('invitation_text', models.TextField(help_text='از {name} برای قرار دادن نام شخص و از {link} برای لینک دعوت استفاده کنید.', verbose_name='متن پیام دعوت')),
                ('thank_you_text', models.TextField(blank=True, null=True, verbose_name='متن تشکر از حضور')),
                ('missed_you_text', models.TextField(blank=True, null=True, verbose_name='متن عدم حضور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مهمانی',
                'verbose_name_plural': 'مهمانی\u200cها',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='حوزه فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حوزه کاری',
                'verbose_name_plural': 'حوزه\u200cهای کاری',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.jobcategory', verbose_name='حوزه فعالیت')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_present', models.BooleanField(default=False, verbose_name='حاضر بود؟')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت حضور')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.event', verbose_name='مهمانی')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.member', verbose_name='عضو دعوت شده')),
            ],
            options={
                'verbose_name': 'مهمان',
                'verbose_name_plural': 'مهمانان',
                'unique_together': {('event', 'member')},
            },
        ),
    ]
