# Generated by Django 6.0.6 on 2026-08-04 21:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مهمانی')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='شهر')),
                ('venue_name', models.CharField(max_length=200, verbose_name='نام مکان برگزاری')),
                ('event_date', models.DateField(db_index=True, verbose_name='تاریخ برگزاری')),
                ('event_time', models.TimeField(verbose_name='ساعت شروع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار برگزاری'), ('active', 'در حال برگزاری'), ('completed', 'پایان یافته')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت مهمانی')),
                ('invitation_text', models.TextField(blank=True, default='', verbose_name='متن پیام دعوت')),
                ('thank_you_text', models.TextField(blank=True, default='', verbose_name='متن تشکر از حضور')),
                ('missed_you_text', models.TextField(blank=True, default='', verbose_name='متن عدم حضور')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مهمانی',
                'verbose_name_plural': 'مهمانی\u200cها',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان عکس/رویداد')),
                ('image', models.ImageField(upload_to='event_gallery/', verbose_name='عکس')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='تاریخ رویداد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عکس گالری مهمانی',
                'verbose_name_plural': 'گالری مهمانی\u200cها',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='حوزه فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حوزه کاری',
                'verbose_name_plural': 'حوزه\u200cهای کاری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='BusinessLink', max_length=100, verbose_name='نام فرستنده')),
                ('invitation_template', models.TextField(default='{full_name} عزیز، شما به مهمانی {event_name} دعوت شده\u200cاید.\nشهر: {city}\nمکان: {venue_name}\nتاریخ: {event_date}\nساعت: {event_time}\nلینک جزئیات: {poster_url}', verbose_name='قالب پیام دعوت')),
                ('thank_you_template', models.TextField(default='{full_name} عزیز، از حضور شما در {event_name} سپاسگزاریم.', verbose_name='قالب پیام تشکر')),
                ('missed_you_template', models.TextField(default='{full_name} عزیز، جای شما در {event_name} خالی بود. امیدواریم برنامه بعدی همراه ما باشید.', verbose_name='قالب پیام عدم حضور')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.jobcategory', verbose_name='حوزه فعالیت')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('invited', 'دعوت شد'), ('attended', 'حضور داشت'), ('absent', 'غایب بود')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت دعوت')),
                ('is_present', models.BooleanField(db_index=True, default=False, verbose_name='حاضر بود؟')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت حضور')),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال دعوت')),
                ('thank_you_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیام تشکر')),
                ('missed_you_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیام عدم حضور')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.event', verbose_name='مهمانی')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_guests', to='core.member', verbose_name='عضو دعوت\u200cشده')),
            ],
            options={
                'verbose_name': 'مهمان',
                'verbose_name_plural': 'مهمانان',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_event_member')],
            },
        ),
    ]
