# Generated by Django 6.0.6 on 2026-07-13 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان عکس/رویداد')),
                ('image', models.ImageField(upload_to='event_gallery/', verbose_name='عکس')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='تاریخ رویداد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عکس گالری مهمانی',
                'verbose_name_plural': 'گالری مهمانی\u200cها',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['name'], 'verbose_name': 'حوزه کاری', 'verbose_name_plural': 'حوزه\u200cهای کاری'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at'], 'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
        migrations.AlterUniqueTogether(
            name='eventguest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AddField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventguest',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال دعوت'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='missed_you_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیام عدم حضور'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='thank_you_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیام تشکر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(db_index=True, verbose_name='تاریخ برگزاری'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_text',
            field=models.TextField(blank=True, default='', verbose_name='متن پیام دعوت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='missed_you_text',
            field=models.TextField(blank=True, default='', verbose_name='متن عدم حضور'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار برگزاری'), ('active', 'در حال برگزاری'), ('completed', 'پایان یافته')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت مهمانی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thank_you_text',
            field=models.TextField(blank=True, default='', verbose_name='متن تشکر از حضور'),
        ),
        migrations.AlterField(
            model_name='eventguest',
            name='is_present',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حاضر بود؟'),
        ),
        migrations.AlterField(
            model_name='eventguest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_guests', to='core.member', verbose_name='عضو دعوت\u200cشده'),
        ),
        migrations.AlterField(
            model_name='member',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.jobcategory', verbose_name='حوزه فعالیت'),
        ),
        migrations.AddConstraint(
            model_name='eventguest',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='unique_event_member'),
        ),
    ]
